# RoverUtils.cmake
# Helper functions for declaring engine targets.

include_guard(GLOBAL)

# ---------------------------------------------------------------------------
# rover_add_library(<name>
#     [SOURCES <files...>]
#     [PUBLIC_DEPS <targets...>]
#     [PRIVATE_DEPS <targets...>]
#     [INTERFACE_DEPS <targets...>]
#     [INCLUDE_DIRS <dirs...>]
#     [FOLDER <ide_folder>])
#
# Standard engine static library wrapper. Wires include path to ROVER_ROOT_DIR
# so engine code uses repo-root-relative includes ("core/...", "services/...")
# in the Godot style. Applies Rover::CompileFlags PRIVATE.
# ---------------------------------------------------------------------------
function(rover_add_library NAME)
    cmake_parse_arguments(ARG
        ""
        "FOLDER"
        "SOURCES;PUBLIC_DEPS;PRIVATE_DEPS;INTERFACE_DEPS;INCLUDE_DIRS"
        ${ARGN})

    if (NOT ARG_SOURCES)
        message(FATAL_ERROR "[Rover] rover_add_library(${NAME}): SOURCES is required")
    endif ()

    add_library(${NAME} STATIC ${ARG_SOURCES})

    target_include_directories(${NAME} PUBLIC "${ROVER_ROOT_DIR}")
    if (ARG_INCLUDE_DIRS)
        target_include_directories(${NAME} PUBLIC ${ARG_INCLUDE_DIRS})
    endif ()

    if (ARG_PUBLIC_DEPS)
        target_link_libraries(${NAME} PUBLIC ${ARG_PUBLIC_DEPS})
    endif ()
    if (ARG_PRIVATE_DEPS)
        target_link_libraries(${NAME} PRIVATE ${ARG_PRIVATE_DEPS})
    endif ()
    if (ARG_INTERFACE_DEPS)
        target_link_libraries(${NAME} INTERFACE ${ARG_INTERFACE_DEPS})
    endif ()

    target_link_libraries(${NAME} PRIVATE Rover::CompileFlags)

    if (ARG_FOLDER)
        set_target_properties(${NAME} PROPERTIES FOLDER "${ARG_FOLDER}")
    endif ()
endfunction()

# ---------------------------------------------------------------------------
# rover_glob_sources(<out_var> <dir>)
#
# Recursively glob *.cpp / *.c / *.h / *.hpp under <dir>, relative to the
# current source directory. Configure-time only; users must reconfigure
# after adding files.
# ---------------------------------------------------------------------------
function(rover_glob_sources OUT_VAR DIR)
    file(GLOB_RECURSE _sources CONFIGURE_DEPENDS
        "${DIR}/*.cpp"
        "${DIR}/*.c"
        "${DIR}/*.h"
        "${DIR}/*.hpp"
    )
    set(${OUT_VAR} "${_sources}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# rover_collect_modules(<out_enabled_var> <modules_dir>)
#
# Populate <out_enabled_var> with a list of enabled module names by scanning
# subdirectories of <modules_dir>. A module <name> is enabled when option
# ROVER_MODULE_<NAME> (uppercased) is ON.
# ---------------------------------------------------------------------------
function(rover_collect_modules OUT_VAR MODULES_DIR)
    set(_enabled "")
    file(GLOB _candidates RELATIVE "${MODULES_DIR}" "${MODULES_DIR}/*")
    foreach (_entry IN LISTS _candidates)
        if (IS_DIRECTORY "${MODULES_DIR}/${_entry}")
            string(TOUPPER "${_entry}" _entry_upper)
            if (ROVER_MODULE_${_entry_upper})
                list(APPEND _enabled "${_entry}")
            endif ()
        endif ()
    endforeach ()
    set(${OUT_VAR} "${_enabled}" PARENT_SCOPE)
endfunction()

# ---------------------------------------------------------------------------
# rover_generate_module_registration(<output_file> <module_names...>)
#
# Emit a generated source that defines register_module_types() and
# unregister_module_types() calling each module's
# register_<name>_types() / unregister_<name>_types() in declared order.
# ---------------------------------------------------------------------------
function(rover_generate_module_registration OUT_FILE)
    set(_modules ${ARGN})

    set(_includes "")
    set(_register_calls "")
    set(_unregister_calls "")
    foreach (_m IN LISTS _modules)
        string(APPEND _includes "#include \"modules/${_m}/register_types.h\"\n")
        string(APPEND _register_calls   "    register_${_m}_types();\n")
        set(_unregister_calls "    unregister_${_m}_types();\n${_unregister_calls}")
    endforeach ()

    file(WRITE "${OUT_FILE}"
"// Generated by rover_generate_module_registration. Do not edit.
#include \"modules/register_module_types.h\"

${_includes}
namespace rover {

void register_module_types() {
${_register_calls}}

void unregister_module_types() {
${_unregister_calls}}

} // namespace rover
")
endfunction()
