#pragma once

#include "core/typedefs.h"

#include <string>
#include <unordered_map>

namespace rover
{

    // AssetID is a stable u64 generated by the registry. 0 is reserved for
    // "invalid". Phase 2 uses sequential ids; Phase 3 will switch to UUIDv4 once
    // we have a portable random source in core/.
    using AssetID                      = u64;
    constexpr AssetID INVALID_ASSET_ID = 0;

    enum class AssetKind : u8
    {
        Unknown,
        Scene,
        Mesh,
        Texture,
        Material,
        Shader,
    };

    struct AssetEntry
    {
        AssetID     id   = INVALID_ASSET_ID;
        AssetKind   kind = AssetKind::Unknown;
        std::string virtual_path; // e.g. "res://meshes/cube.rmesh"
        std::string source_path;  // resolved native path
    };

    // ---------------------------------------------------------------------------
    // AssetRegistry: in-memory mapping of virtual asset paths to stable IDs
    // plus minimal metadata. Phase 2 keeps the registry process-local; the
    // disk-backed `<project>/.rover/registry.json` will arrive with the editor
    // CLI in Phase 3.
    // ---------------------------------------------------------------------------
    class AssetRegistry
    {
    public:
        [[nodiscard]] static AssetRegistry& get();

        AssetRegistry(const AssetRegistry&)            = delete;
        AssetRegistry& operator=(const AssetRegistry&) = delete;

        // Returns the existing id when `virtual_path` is already registered;
        // otherwise registers a new entry and returns its fresh id.
        AssetID register_asset(AssetKind kind, std::string virtual_path, std::string source_path = {});

        // Removes the entry; returns true if the asset was present.
        bool unregister(AssetID id);

        [[nodiscard]] const AssetEntry* find(AssetID id) const;
        [[nodiscard]] AssetID           find_id(const std::string& virtual_path) const;

        // Total registered entries. Mostly for tests / editor stats.
        [[nodiscard]] usize size() const noexcept { return by_id_.size(); }

        // Wipes every entry. Used by tests; production should not need it.
        void clear();

    private:
        AssetRegistry()  = default;
        ~AssetRegistry() = default;

        AssetID                                  next_id_ = 1;
        std::unordered_map<AssetID, AssetEntry>  by_id_;
        std::unordered_map<std::string, AssetID> by_path_;
    };

} // namespace rover
